grpc:
  security:
    enabled: false

spring:
  config:
    import: optional:file:src/main/resources/.env[.properties]
  application:
    name: lmao
  web:
    resources:
      add-mappings: false
  devtools:
    restart:
      enabled: true 
      trigger-file: .reloadtrigger 
      additional-paths: src/main/java 
      poll-interval: 100 
      quiet-period: 50    
    livereload:
      enabled: true
  data:
    mongodb:
      uri: ${mongo_uri}
      database: ${mongo_database_name}
      auto-index-creation: true
  mail:
    host: ${smtp_host}
    port: ${smtp_port}
    username: ${smtp_username}
    password: ${smtp_passwd}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connection timeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.write timeout: 5000

server:
  port: 8080  
  error:
    whitelabel:
      enabled: false  
    include-message: always  
    include-binding-errors: always  
    include-stacktrace: never

gprc:
  server:
    it

config:
  hmac_key: ${hmac_secret_ket}
  server-domain: ${SERVER_DOMAIN}
  sso-domain:
    verifyTokenApi: ${VERIFY_TOKEN_API}
  invitation-expired-for: "12h"
